### ISSUE TITLE
Improve Documentation Setup: Recipes and Common Patterns

### ISSUE THREAD

**Issue by francisrstokes** [francisrstokes/hexnut#8]
The idea is to create a dedicated page for recipes and common patterns.

These are currently found in the main readme, but could be organised and indexed here, and thus easily linked to form other places

**Comment by moimikey** [comment]
enable CORS in 1-2-3!

```
const Hexnut = require('hexnut')
const cors = require('cors')
const app = new Hexnut({ port: 8080 })
app.use(cors())
app.start()
```

**Comment by francisrstokes** [comment]
I imagine this would need a wrapper? Otherwise it's a very beautiful coincidence! I think you'd actually need to have something more like:

```javascript
const Hexnut = require('hexnut')
const express = require('express')
const http = require('http')
const cors = require('cors')

const exApp = express();
exApp.use(cors());
const server = http.createServer(exApp);

const app = new Hexnut({ server })
app.start()
```

Because Hexnut cannot actually use express middleware. It can however share the same underlying server object, like above.

**Comment by moimikey** [comment]
at the time of writing, I hadn't considered that while hexnut has an express-like api, it doesn't _use_ express. so yes, does need to be wrapped. which in  the above case would actually work then, given you can pass `server` to hexnut.

**Comment by moimikey** [comment]
corrected. server should  be passed as an option.

```javascript
const Hexnut = require('hexnut')
const cors = require('cors')
const express = require('express')()
const http = require('http')
const https = require('https')

let withSSL = true;

express.use(cors())

const server = withSSL ? new https.createServer({ cert, key }, express) : new http.createServer(express)
const app = new Hexnut({ port: 8080, server })

app.start()
```

voila!
